### PR TITLE
Combined ulge file

### PR DESCRIPTION
**Pull request by jnippula**
Combine encrypted log data and symmetric key into one single .ulge file.

### CODE REVIEW

**Comment by jlaitine** [comment]
LGTM! I'd like see this  offered upstream first though to avoid merge conflicts later...

**Comment by jnippula** [comment]
> LGTM! I'd like see this offered upstream first though to avoid merge conflicts later...

Yes, I created PR's for upstream already for code and documentation:
https://github.com/PX4/PX4-Autopilot/pull/24024
https://github.com/PX4/PX4-user_guide/pull/3468

**Comment by jnippula** [comment]
> Upstream PR version still needs to be verified with HW (e.g. fmu-v5x) before creating the PR.

**Comment by jnippula** [comment]
Now commits are cherry-picked from upstream

**Review by jlaitine — APPROVED** [review]

**Pull request merged**
