### PR TITLE
Port from 1.13_fc_only to main [1/4]

### PR DESCRIPTION
**Pull request by t-salminen**
Telem_test application and airspeed sensor fixes ported from 1.13_fc_only:

-telem_test application runs simple write/read loopback test between 2 telemetry uart ports (HW test)
-MS4525DO and SDP3X sensor I2C default speed set to 400 kHz and related sensor start workarounds removed

### CODE REVIEW

**Comment by t-salminen** [comment]
Submodules must be updated before merge

**Comment by t-salminen** [comment]
@kordets , this PR has the i2c default speed fixes for airspeed sensor startup

**Comment by jlaitine** [comment]
How about saluki-pi ( nowdays aka FMU2), is this neede there as well? No submodule update for that one?

**Review by jlaitine — APPROVED** [review]

**Comment by t-salminen** [comment]
Submodules updated

**Pull request merged**
