### PR TITLE
Add secure mavlink

### PR DESCRIPTION
**Pull request by jnippula**

### CODE REVIEW

**Comment by jnippula** [comment]
Wait for boards/ssrc submodules to be merged first. Then update submodules to point "main" branch

**Comment by jnippula** [comment]
Maybe better to not disable uxrce client altogether yet, but only when secure mavlink is active. Then we don't left any non-hardened interfaces available on the side of secmav.

**Comment by jnippula** [comment]
Wait for submodules to be merged

**Review by jlaitine — APPROVED** [review]

**Comment by jnippula** [comment]
Just noticed that the secure-udp-proxy module had still the feature branch version, now merged that to module main and updated px4-firmware branch for this PR. Waiting for CI build and quick verification before merging this.

**Review by kjyrinki-unikie — APPROVED** [review]

**Comment by jnippula** [comment]
Sec-mavlink connection verified with Saluki-v2 and QGC with reverse-proxy

**Pull request merged**
