### PR TITLE
mpfs/bootloader: Don't attempt eMMC write, if is not open

### PR DESCRIPTION
**Pull request by pussuw**
Tiny fix, don't attempt eMMC write if the media is not mounted / open

### CODE REVIEW

**Review by jlaitine — APPROVED** [review]
LGTM

**Comment by jlaitine** [comment]
It is not really an error to write to -1 fd, though. Please also verify that flashing doesn't succeed if mount fails; this would be a very confusing bug since the device would boot right after flashing but not any more after poweroff...

**Comment by pussuw** [comment]
I can do that in another PR, if it is not handled yet

**Comment by jlaitine** [comment]
> I can do that in another PR, if it is not handled yet

cool. It was previosly handled implicitly by write failing when writing to a non existing fd. I wasn't sure if it is handled now, when it doesn't write at all :)

**Comment by pussuw** [comment]
> > I can do that in another PR, if it is not handled yet
> 
> cool. It was previosly handled implicitly by write failing when writing to a non existing fd. I wasn't sure if it is handled now, when it doesn't write at all :)

I cannot find the procedure that propagates this write failure status outside of the procedure itself. Can you provide the specific location that needs to be fixed ?

**Comment by jlaitine** [comment]
> > > I can do that in another PR, if it is not handled yet
> > 
> > cool. It was previosly handled implicitly by write failing when writing to a non existing fd. I wasn't sure if it is handled now, when it doesn't write at all :)
> 
> I cannot find the procedure that propagates this write failure status outside of the procedure itself. Can you provide the specific location that needs to be fixed ?
> 
> I just have a severe lack of understanding what these procedures are supposed to do so I would very much appreciate any guidance :)

#196, which was fixing exactly that bug (don't remember the jira # right now) but I forgot to merge it. Now it conflicts, need to do again next week.

**Comment by pussuw** [comment]
> > > > I can do that in another PR, if it is not handled yet
> > > 
> > > 
> > > cool. It was previosly handled implicitly by write failing when writing to a non existing fd. I wasn't sure if it is handled now, when it doesn't write at all :)
> > 
> > 
> > I cannot find the procedure that propagates this write failure status outside of the procedure itself. Can you provide the specific location that needs to be fixed ?
> > I just have a severe lack of understanding what these procedures are supposed to do so I would very much appreciate any guidance :)
> 
> #196, which was fixing exactly that bug (don't remember the jira # right now) but I forgot to merge it. Now it conflicts, need to do again next week.

You can always force push revert :D

**Pull request merged**
