### PR TITLE
UAVCAN driver fixes for ESC control via CAN support

### PR DESCRIPTION
**Pull request by haitomatic**
- Add some extra UAVCAN params for finer feature control
- Fix UAVCAN task return which destroys CAN socket issue
- Add function to help retrieve board MFGUID
- Cleanups

### CODE REVIEW

**Comment by jlaitine** [comment]
Some generic remarks;

Please pay attention to commit titles, and try to make them more descriptive, so that the title tells what has been done. As an example of the commits in this PR, instead of "fix minor bugs;", you could just use "Disable gps sensor subscription by default" (and merge the other changes in the commits which are related to those). Try to avoid mixing different things in a single commit. It is horrible to read through git log, if there are dozens of "fix a bug" titles....

Another thing is, that these are generic changes to upstream PX4 code, maybe you could upstream them first. They should anyhow be upstreamed eventually, and it makes life easier if you do that first. Then we can stay in sync with upstream PX4 and avoid trouble in the future.

I am fine with the actual code, thanks! :)

**Comment by haitomatic** [comment]
Thanks. I will fix the commits and create another PR.

Also, I just found that 2 weeks back, there was a new commit that basically solved some of the issues this PR tries to solve but our rebased PX4 was before that.
https://github.com/PX4/PX4-Autopilot/commit/33e39d68f77222978637fddd93c3a455a1997e78
I think I can pull this commit, test it and apply the remaining changes on top of it. This will come in the same PR I mentioned.

Some of the fixes in this PR, I think, are for our own problems I discovered during previous CAN flight tests. Probably, we should just keep them in our fork, not upstream.

What do you think is the best way?

**Comment by haitomatic** [comment]
anyhow, I make another PR https://github.com/tiiuae/px4-firmware/pull/288 doing exactly the above

**Comment by pussuw** [comment]
Another generic remark is that when developing a feature, it is natural that some fixes / clean-up etc are needed. However, these fix/clean-up commits should always be squashed into the commit that needs fixing or clean-up.

Take this as an example, the work flow might go like this:
commit 1: Implement great feature XXX
commit 2: Fix bug #1 in XXX
commit 3: Fix bug #2 in XXX
commit 4: Modify XXX according to comments 
commit 5: Clean up after modifications, all done

Ok, now everything is done! But what should we push to the remote repository ? The only interesting thing is obviously that you have implemented XXX. So the commit history should be squashed into 1 commit containing all 5 patches:
commit 1: Implement great feature XXX

And then -> push to remote

It is then a matter of taste if the entire history should be visible in the PR, in my opinion it is not necessary, but what really matters is that the remote repository does not end up with a bunch of "fixed bug" type of commit messages that are very difficult to follow when skimming through git history.

**Comment by pussuw** [comment]
And a third remark, if there are several unrelated bugs, for example you are developing feature XXX, but during that you find a bug that already exists in the repo, a new separate PR should be made to fix that bug.

**Comment by pussuw** [comment]
I'll give one short example of how I personally do pull requests that receive comments that need fixing:
https://github.com/tiiuae/px4-firmware/pull/162

The original patch contains 1 commit:
- `board_ctrl: Clean up usage of VBUS, nARMED from user/kernelspace`

When I receive comments like "can you change this style" I do the change locally, and make 1 new commit
- `git add . && git commit -m "fix style issue"`
- Then for example `git rebase -i HEAD~2`
- Do fixup for the two commits
- After this only the original commit remains with the style modifications

I personally prefer this style, it gets rid of the uninteresting history (the way I got to the final result), leaving only the final result.

**Comment by jlaitine** [comment]
Please check this PR and close if no longer relevant, thanks 🙂

**Comment by jlaitine** [comment]
Closed this old, stale pr

**Pull request closed without merging**
