### PR TITLE
DP-9127 fw update client integration

### PR DESCRIPTION
**Pull request by jnippula**
Changes:
- version: new function to get git top info (commit count on top of latest tag)
- px4-firmware container image updated to contain full commit-if in json file
- New submodule: src/lib/secure_udp
- New submodule: src/modules/px4_fw_update_client
- boards/ssrc/common updated (devstate.h file updated for FC-OTA)
- boards/ssrc/saluki-v3 updated (enable FC-OTA client build and call it in start script)

px4 update client is running in the background, but does not do anything if there is no update server available in MC to connect. Also, there is R&D certificate flag to disable update client start (FEATURE_DISABLE_FCOTA_UPDATE)

### CODE REVIEW

**Comment by jnippula** [comment]
Wait for boards/ssrc/saluki-v3 submodule to be updated with px4_fw_update_client enabling to update submodule here.

**Comment by jnippula** [comment]
saluki-v3 submodule updated

**Comment by jnippula** [comment]
Need to update fpga/bootloader to point to latest bootloader version, which contains the devstate.h header updates for FC-OTA.

**Review by jpaali — APPROVED** [review]
LGTM

**Review by kjyrinki-unikie — APPROVED** [review]

**Pull request merged**
