### PR TITLE
netconfig: Change IP addressing to match the new SSRC scheme

### PR DESCRIPTION
**Pull request by jlaitine**
- Change drone's IP last byte to start at mav_id (1 in case of one FC)
- Use IP last byte 2 high bits to denote redundant autopilot within same drone

### CODE REVIEW

**Comment by jlaitine** [comment]
Tested to work, need to update in sync with the rest

**Review by jpaali — APPROVED** [review]
LGTM

**Comment by jlaitine** [comment]
Is it time to merge this one already? Is the IP change done in MC side?

**Comment by jpaali** [comment]
I think we will merge this in this week. MC side changes has not been integrated either.

**Comment by jlaitine** [comment]
"this week" passed almost 2 months ago. Merging this in now, MC side changes may follow.

**Pull request merged**
